### Question 1
###### What's the version of Pandas that you installed?

In [2]:
import pandas as pd

In [4]:
pd.__version__

'1.5.3'

### Question 2
##### How many columns are in the dataset?


In [28]:
url= 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'

In [29]:
df = pd.read_csv(url)
df.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [30]:
df.shape

(20640, 10)

In [31]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

### Question 3: Select columns with missing data


In [33]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### Question 4: Number of unique values in the 'ocean_proximity' column


In [34]:
df.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

In [41]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

### Question 5: Average value of the 'median_house_value' for the houses near the bay

In [42]:
df.head(1)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY

In [57]:
mean_value = df.groupby('ocean_proximity').get_group('NEAR BAY')['median_house_value'].mean().round()
mean_value

259212.0

#### Question 6

In [58]:
df.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY

###### Calculate the average of total_bedrooms column in the dataset.

In [67]:
tot_bedrooms_avg = df['total_rooms'].mean()
tot_bedrooms_avg.round()

2636.0

###### Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

In [62]:
col_mean= tot_bedrooms_avg.mean().round()
col_mean

2636.0

In [65]:
updated_df = df.fillna(col_mean)
updated_df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

###### Now, calculate the average of total_bedrooms again.

In [68]:
updated_tot_bed_avg = updated_df['total_bedrooms'].mean()
updated_tot_bed_avg.round()

559.0

###### Has it changed?
##### YES

### Question 7


##### What's the value of the last element of w?

##### Select all the options located on islands.

In [72]:
updated_df.groupby('ocean_proximity').get_group('ISLAND')['ocean_proximity'].count()

5

##### Select only columns housing_median_age, total_rooms, total_bedrooms.

In [74]:
subset = updated_df[['housing_median_age','total_rooms', 'total_bedrooms']]
subset

housing_median_age  total_rooms  total_bedrooms
0                    41.0        880.0           129.0
1                    21.0       7099.0          1106.0
2                    52.0       1467.0           190.0
3                    52.0       1274.0           235.0
4                    52.0       1627.0           280.0
...                   ...          ...             ...
20635                25.0       1665.0           374.0
20636                18.0        697.0           150.0
20637                17.0       2254.0           485.0
20638                18.0       1860.0           409.0
20639                16.0       2785.0           616.0

[20640 rows x 3 columns]

##### Get the underlying NumPy array. Let's call it X.

In [75]:
import numpy as np

In [76]:
X = np.array(subset)
X

array([[  41.,  880.,  129.],
       [  21., 7099., 1106.],
       [  52., 1467.,  190.],
       ...,
       [  17., 2254.,  485.],
       [  18., 1860.,  409.],
       [  16., 2785.,  616.]])

##### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [77]:
XT = np.transpose(X) 

In [82]:
XTX = np.matmul(X, XT)
XTX

array([[  792722.,  6390655.,  1317602., ...,  2046782.,  1690299.,
         2530920.],
       [ 6390655., 51619478., 10625465., ..., 16537913., 13656872.,
        20452347.],
       [ 1317602., 10625465.,  2190893., ...,  3399652.,  2807266.,
         4203467.],
       ...,
       [ 2046782., 16537913.,  3399652., ...,  5316030.,  4391111.,
         6576422.],
       [ 1690299., 13656872.,  2807266., ...,  4391111.,  3627205.,
         5432332.],
       [ 2530920., 20452347.,  4203467., ...,  6576422.,  5432332.,
         8135937.]])

##### Compute the inverse of XTX.

In [83]:
inverse = np.linalg.inv(XTX)
inverse

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

##### Create an array y with values [950, 1300, 800, 1000, 1300].

In [85]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

##### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [91]:
temp = np.matmul(XT,inverse)
temp

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [94]:
w = np.multiply(temp, y)
w

ValueError: operands could not be broadcast together with shapes (3,20640) (5,) 